version: 2.1
orbs:
  node: circleci/node@1.1.6
  browser-tools: circleci/browser-tools@1.0.0

jobs:
  building:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run: npm install
            - run: npm run test-headless
            - run: npm install --save-dev firebase-tools

  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - run: npm run test-headless

  deploy-club:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build:club
            - run: './node_modules/.bin/firebase deploy --only hosting:club --token=$FIREBASE_TOKEN'

  deploy-social:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build:social
            - run: './node_modules/.bin/firebase deploy --only hosting:social --token=$FIREBASE_TOKEN'

  deploy-rental:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run build:rental
            - run: './node_modules/.bin/firebase deploy --only hosting:rental --token=$FIREBASE_TOKEN'

workflows:
    building-and-deployment:
      jobs:
        - building
        # - test:
        #     requires:
        #       - building
        - deploy-club:
            requires:
              - building
            filters:
              branches:
                only:
                  - deploy-product-club
        - deploy-social:
            requires:
              - building
            filters:
              branches:
                only:
                  - deploy-product-social
        - deploy-rental:
            requires:
              - building
            filters:
              branches:
                only:
                  - deploy-product-rental
