version: 2
jobs:
  deployBase:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm install --save-dev firebase-tools
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run prod-build
      - run: './node_modules/.bin/firebase deploy --only hosting:club --token=$FIREBASE_TOKEN'

workflows:
  version: 2
  building-and-deployment:
    jobs:
      - deployBase:
          filters:
            branches:
              only:
                - integracion-continua

