version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-club:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install --save-dev firebase-tools
            - run: npm run build:club
            - run: './node_modules/.bin/firebase deploy --only hosting:club --token=$FIREBASE_TOKEN'

workflows:
    building-and-deployment:
      jobs:
        - deploy-club:
            filters:
              branches:
                only:
                  - deploy-product-club
